language: rust
cache: cargo
rust:
  - nightly

services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - echo "DATABASE_URL=postgres://postgres@localhost/travis_ci_test" > .env
  - cargo install diesel_cli --no-default-features --features=postgres || echo "diesel_cli already installed"
  - diesel migration run

script:
  - cargo test
