language: rust
cache: cargo
rust:
  - nightly

services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - cargo build
  - cargo install diesel_cli
  - diesel migration run
  - cargo test --test mod pages -- --test-threads=1
  - cargo test --test mod users -- --test-threads=1
  - cargo test --test mod session -- --test-threads=1
  - cargo test --test mod pages -- --test-threads=1
